apiVersion: v1
kind: Pod
metadata:
  name: pod-restored
  namespace: <namespace>
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: restored-volume
  volumes:
  - name: restored-volume
    persistentVolumeClaim:
      claimName: restored-pvc
