# kubectl apply -f mongo-pod.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
spec:
  nodeSelector:
    kubernetes.io/hostname: kworker02.lab.local
  containers:
  - name: mongo
    image: mongo:5.0
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_DATABASE
      value: "financedb"
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
    - name: mongo-init
      mountPath: /docker-entrypoint-initdb.d/mongo-init.js
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc
  - name: mongo-init
    configMap:
      name: mongo-init-config